import { theme } from "antd";
import type { ThemeConfig } from "antd";

export const marathonDosPalette = {
  black: "#000000",
  void: "#050505",
  panel: "#0f0f0f",
  surface: "#1c1c1c",
  grid: "#2b2b2b",
  muted: "#717171",
  text: "#f5f5f0",
  primary: "#c0fe04",
  primaryDeep: "#86b400",
  warning: "#ff9b2f",
  error: "#f24723",
} as const;

export const marathonDosFontStacks = {
  ui: "\"Azeret Mono\", \"SFMono-Regular\", \"Menlo\", monospace",
  display: "\"Oxanium\", \"Azeret Mono\", sans-serif",
  displaySecondary: "\"Doto\", \"Oxanium\", \"Azeret Mono\", sans-serif",
} as const;

export const marathonDosTheme: ThemeConfig = {
  algorithm: [theme.darkAlgorithm, theme.compactAlgorithm],
  token: {
    colorPrimary: marathonDosPalette.primary,
    colorInfo: marathonDosPalette.primary,
    colorSuccess: "#94db19",
    colorWarning: marathonDosPalette.warning,
    colorError: marathonDosPalette.error,
    colorLink: marathonDosPalette.primary,
    colorTextBase: marathonDosPalette.text,
    colorBgBase: marathonDosPalette.black,
    colorBorder: marathonDosPalette.muted,
    colorBorderSecondary: marathonDosPalette.grid,
    colorSplit: marathonDosPalette.grid,
    colorText: marathonDosPalette.text,
    colorTextSecondary: "#a6a6a6",
    colorTextTertiary: marathonDosPalette.muted,
    colorTextQuaternary: "#5c5c5c",
    colorBgContainer: marathonDosPalette.panel,
    colorBgElevated: "#131313",
    colorBgLayout: marathonDosPalette.void,
    colorFillSecondary: "rgba(192, 254, 4, 0.08)",
    colorFillTertiary: "rgba(192, 254, 4, 0.12)",
    colorFillQuaternary: "rgba(255, 255, 255, 0.05)",
    controlItemBgHover: "rgba(192, 254, 4, 0.08)",
    controlItemBgActive: "rgba(192, 254, 4, 0.14)",
    controlItemBgActiveHover: "rgba(192, 254, 4, 0.18)",
    controlOutline: "rgba(192, 254, 4, 0.26)",
    controlOutlineWidth: 1,
    lineWidth: 1,
    fontFamily: marathonDosFontStacks.ui,
    fontFamilyCode: marathonDosFontStacks.ui,
    fontSize: 13,
    fontSizeHeading1: 42,
    fontSizeHeading2: 28,
    fontSizeHeading3: 20,
    fontSizeHeading4: 16,
    lineHeight: 1.5,
    wireframe: false,
    borderRadius: 2,
    borderRadiusXS: 0,
    borderRadiusSM: 0,
    borderRadiusLG: 2,
    borderRadiusOuter: 2,
    boxShadow: "none",
    boxShadowSecondary: "0 0 0 1px rgba(192, 254, 4, 0.12)",
    padding: 16,
    paddingLG: 20,
    controlHeight: 40,
    controlHeightSM: 34,
    controlHeightLG: 46,
  },
  components: {
    Button: {
      fontWeight: 600,
      defaultBg: "#101010",
      defaultColor: marathonDosPalette.text,
      defaultBorderColor: marathonDosPalette.muted,
      defaultHoverBg: "#151515",
      defaultHoverColor: marathonDosPalette.primary,
      defaultHoverBorderColor: marathonDosPalette.primary,
      defaultActiveBg: "#0d0d0d",
      defaultActiveColor: marathonDosPalette.primary,
      defaultActiveBorderColor: marathonDosPalette.primaryDeep,
      primaryColor: marathonDosPalette.black,
      defaultShadow: "none",
      primaryShadow: "none",
      dangerShadow: "none",
      textHoverBg: "rgba(192, 254, 4, 0.08)",
      linkHoverBg: "transparent",
      contentFontSize: 13,
      contentFontSizeLG: 14,
      contentFontSizeSM: 12,
      paddingInline: 18,
      paddingInlineLG: 22,
      paddingInlineSM: 14,
    },
    Input: {
      addonBg: "#080808",
      hoverBg: "#101010",
      activeBg: "#101010",
      hoverBorderColor: marathonDosPalette.primary,
      activeBorderColor: marathonDosPalette.primary,
      activeShadow: "0 0 0 2px rgba(192, 254, 4, 0.16)",
      errorActiveShadow: "0 0 0 2px rgba(242, 71, 35, 0.18)",
      warningActiveShadow: "0 0 0 2px rgba(255, 155, 47, 0.18)",
      inputFontSize: 13,
      inputFontSizeLG: 14,
      inputFontSizeSM: 12,
      paddingBlock: 8,
      paddingBlockLG: 10,
      paddingBlockSM: 6,
      paddingInline: 12,
      paddingInlineLG: 14,
      paddingInlineSM: 10,
    },
    Card: {
      headerBg: "#090909",
      actionsBg: "#090909",
      extraColor: marathonDosPalette.primary,
      headerFontSize: 12,
      headerFontSizeSM: 11,
      headerHeight: 52,
      headerHeightSM: 44,
      bodyPadding: 20,
      bodyPaddingSM: 16,
      headerPadding: 20,
      headerPaddingSM: 16,
      tabsMarginBottom: 16,
    },
    Typography: {
      titleMarginBottom: "0.3em",
      titleMarginTop: "1.1em",
    },
  },
};
