import type { CueDefinition, NoiseCueName } from "./noiseCueTypes.js";

export const noiseCueDefinitions = {
  click: {
    outputGain: 0.46,
    layers: [
      {
        kind: "tone",
        start: 0,
        duration: 0.036,
        gain: 0.14,
        attack: 0.001,
        decay: 0.036,
        waveform: "sawtooth",
        frequency: 2140,
        endFrequency: 1320,
        detune: 2,
        filterType: "bandpass",
        filterFrequency: 2800,
        q: 2.2,
      },
      {
        kind: "tone",
        start: 0.001,
        duration: 0.028,
        gain: 0.1,
        attack: 0.001,
        decay: 0.028,
        waveform: "triangle",
        frequency: 1360,
        endFrequency: 860,
        detune: -7,
        filterType: "highpass",
        filterFrequency: 900,
        q: 0.8,
      },
      {
        kind: "noise",
        start: 0,
        duration: 0.018,
        gain: 0.08,
        attack: 0.001,
        decay: 0.018,
        filterType: "highpass",
        filterFrequency: 3600,
        q: 0.7,
        playbackRate: 1.25,
      },
    ],
  },
  confirm: {
    outputGain: 0.44,
    layers: [
      {
        kind: "tone",
        start: 0,
        duration: 0.06,
        gain: 0.16,
        attack: 0.002,
        decay: 0.06,
        waveform: "sawtooth",
        frequency: 520,
        endFrequency: 620,
        detune: -4,
        filterType: "lowpass",
        filterFrequency: 1800,
        q: 0.9,
      },
      {
        kind: "tone",
        start: 0.055,
        duration: 0.07,
        gain: 0.17,
        attack: 0.002,
        decay: 0.07,
        waveform: "triangle",
        frequency: 780,
        endFrequency: 940,
        detune: 2,
        filterType: "bandpass",
        filterFrequency: 2200,
        q: 1.6,
      },
      {
        kind: "tone",
        start: 0.115,
        duration: 0.095,
        gain: 0.16,
        attack: 0.002,
        decay: 0.095,
        waveform: "triangle",
        frequency: 1180,
        endFrequency: 1460,
        detune: 7,
        filterType: "highpass",
        filterFrequency: 1200,
        q: 0.7,
      },
      {
        kind: "noise",
        start: 0,
        duration: 0.024,
        gain: 0.03,
        attack: 0.001,
        decay: 0.024,
        filterType: "bandpass",
        filterFrequency: 3200,
        q: 1.4,
        playbackRate: 1.15,
      },
    ],
  },
  error: {
    outputGain: 0.42,
    layers: [
      {
        kind: "tone",
        start: 0,
        duration: 0.095,
        gain: 0.14,
        attack: 0.001,
        decay: 0.095,
        waveform: "sawtooth",
        frequency: 460,
        endFrequency: 220,
        detune: -10,
        filterType: "lowpass",
        filterFrequency: 1400,
        q: 1.2,
      },
      {
        kind: "tone",
        start: 0.018,
        duration: 0.11,
        gain: 0.12,
        attack: 0.001,
        decay: 0.11,
        waveform: "square",
        frequency: 356,
        endFrequency: 176,
        detune: 7,
        filterType: "bandpass",
        filterFrequency: 920,
        q: 1.4,
      },
      {
        kind: "noise",
        start: 0.01,
        duration: 0.07,
        gain: 0.04,
        attack: 0.001,
        decay: 0.07,
        filterType: "bandpass",
        filterFrequency: 1800,
        q: 0.8,
        playbackRate: 0.82,
      },
    ],
  },
  boot: {
    outputGain: 0.38,
    layers: [
      {
        kind: "tone",
        start: 0,
        duration: 0.11,
        gain: 0.12,
        attack: 0.002,
        decay: 0.11,
        waveform: "sawtooth",
        frequency: 240,
        endFrequency: 320,
        detune: -8,
        filterType: "lowpass",
        filterFrequency: 900,
        q: 0.9,
      },
      {
        kind: "tone",
        start: 0.07,
        duration: 0.12,
        gain: 0.12,
        attack: 0.002,
        decay: 0.12,
        waveform: "triangle",
        frequency: 360,
        endFrequency: 520,
        detune: 0,
        filterType: "bandpass",
        filterFrequency: 1400,
        q: 1.1,
      },
      {
        kind: "tone",
        start: 0.145,
        duration: 0.14,
        gain: 0.11,
        attack: 0.002,
        decay: 0.14,
        waveform: "triangle",
        frequency: 540,
        endFrequency: 860,
        detune: 8,
        filterType: "highpass",
        filterFrequency: 900,
        q: 0.7,
      },
      {
        kind: "noise",
        start: 0,
        duration: 0.03,
        gain: 0.025,
        attack: 0.001,
        decay: 0.03,
        filterType: "highpass",
        filterFrequency: 4200,
        q: 0.7,
        playbackRate: 1.3,
      },
    ],
  },
} as const satisfies Record<NoiseCueName, CueDefinition>;
